scrapers:
  packetstorm:
    site_name: "Packet Storm Security"
    base_url: "https://packetstormsecurity.com"
    url: "https://packetstormsecurity.com/search/files/page{0}/?q={1}"
    max_page: 2
  cxsecurity:
    site_name: "CXSecurity"
    base_url: "https://cxsecurity.com/"
    url: "https://cxsecurity.com/search/wlb/DESC/AND/{0}.1999.1.1/{1}/30/{3}/"
    max_page: 2
  zeroday:
    site_name: "0day"
    base_url: "http://0day.today"
    url: "http://0day.today/search?search_request={0}"
    max_page: 1

